FROM openresty/openresty:centos
MAINTAINER potevio
ADD deploy/service-test.conf /etc/nginx/conf.d/service-test.conf
ADD deploy/airport-admin /usr/local/openresty/nginx/html/airport-admin
RUN chmod -R +555 /usr/local/openresty/nginx/html/airport-admin
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
