---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-web-service
  namespace: airport-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: air-web-service
  template:
    metadata:
      labels:
        app: air-web-service
    spec:
      containers:
      - name: nginx-microservice
        image: harbor.yourdomain.com:8443/plane/air-web-service:test
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1500Mi
            cpu: 500m
          limits:
            memory: 2000Mi
            cpu: 1
      restartPolicy: Always
      imagePullSecrets:
      - name: harborsecret

---
apiVersion: v1
kind: Service
metadata:
  name: air-web-service
  namespace: airport-test
spec:
  ports:
  - name: http
    targetPort: 30080
    port: 30080
    nodePort: 30080
  selector:
    app: air-web-service
  type: NodePort

